import logging
import math
import os
import pdb
import sys
from dataclasses import dataclass, field
from typing import Optional, Union, List, Dict, Tuple
import torch
import collections
import random

from datasets import load_dataset

import transformers
from transformers import (
    CONFIG_MAPPING,
    MODEL_FOR_MASKED_LM_MAPPING,
    AutoConfig,
    AutoModelForMaskedLM,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorForLanguageModeling,
    DataCollatorWithPadding,
    HfArgumentParser,
    Trainer,
    TrainingArguments,
    default_data_collator,
    set_seed,
    EvalPrediction,
    BertModel,
    BertForPreTraining,
    RobertaModel
)
from transformers.tokenization_utils_base import BatchEncoding, PaddingStrategy, PreTrainedTokenizerBase
from transformers.trainer_utils import is_main_process
from transformers.data.data_collator import DataCollatorForLanguageModeling
from transformers.file_utils import cached_property, torch_required, is_torch_available, is_torch_tpu_available
# Import our custom models (with OrthoCSE changes)
from simcse.models import RobertaForCL, BertForCL
# Import a custom trainer if needed
from simcse.trainers import CLTrainer

logger = logging.getLogger(__name__)
MODEL_CONFIG_CLASSES = list(MODEL_FOR_MASKED_LM_MAPPING.keys())
MODEL_TYPES = tuple(conf.model_type for conf in MODEL_CONFIG_CLASSES)

@dataclass
class ModelArguments:
    """
    Arguments pertaining to which model/config/tokenizer we are going to fine-tune or train from scratch.
    """

    # HF original
    model_name_or_path: Optional[str] = field(
        default=None,
        metadata={
            "help": "The model checkpoint for weights initialization. Leave None to train from scratch."
        },
    )
    model_type: Optional[str] = field(
        default=None,
        metadata={"help": "If training from scratch, a model type from the list."},
    )
    config_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained config name or path if not same as model_name"}
    )
    tokenizer_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained tokenizer name or path if not same as model_name"}
    )
    cache_dir: Optional[str] = field(
        default=None,
        metadata={"help": "Directory to store pretrained models from huggingface.co"},
    )
    use_fast_tokenizer: bool = field(
        default=True,
        metadata={"help": "Use the fast tokenizer or not."},
    )
    model_revision: str = field(
        default="main",
        metadata={"help": "Version of the model (branch name, tag name or commit id)."},
    )
    use_auth_token: bool = field(
        default=False,
        metadata={"help": "Use the token generated by `transformers-cli login`."},
    )

    # SimCSE arguments
    temp: float = field(
        default=0.05,
        metadata={"help": "Temperature for contrastive softmax."}
    )
    pooler_type: str = field(
        default="cls",
        metadata={"help": "Type of pooler to use (cls, cls_before_pooler, avg, ...)."}
    )
    hard_negative_weight: float = field(
        default=0,
        metadata={"help": "Logit-based weight for hard negatives (only if using 3-sentence input)."}
    )
    do_mlm: bool = field(
        default=False,
        metadata={"help": "Use MLM auxiliary objective or not."}
    )
    mlm_weight: float = field(
        default=0.1,
        metadata={"help": "Weight for MLM objective if `do_mlm` is True."}
    )
    mlp_only_train: bool = field(
        default=False,
        metadata={"help": "Use MLP only during training."}
    )

    # ==========================================
    # Orthonormality arguments (OrthoCSE)
    # ==========================================
    ortho_loss_percent: float = field(
        default=0.0,
        metadata={"help": "Fraction of cross-entropy loss used for orthogonality penalty (0.1 => 10%)."}
    )
    ortho_margin: float = field(
        default=0.0,
        metadata={"help": "Margin threshold for orthogonality. Must be in (0,1)."}
    )


@dataclass
class DataTrainingArguments:
    """
    Arguments about data: dataset path, max_seq_length, etc.
    """
    dataset_name: Optional[str] = field(
        default=None, metadata={"help": "Name of the dataset to use (HuggingFace Datasets)."}
    )
    dataset_config_name: Optional[str] = field(
        default=None, metadata={"help": "Configuration name of the dataset if relevant."}
    )
    overwrite_cache: bool = field(
        default=False, metadata={"help": "Overwrite the cached training sets."}
    )
    validation_split_percentage: Optional[int] = field(
        default=5,
        metadata={"help": "Percentage of train set used as validation if no val split."}
    )
    preprocessing_num_workers: Optional[int] = field(
        default=1,
        metadata={"help": "Number of processes for data preprocessing."}
    )

    train_file: Optional[str] = field(
        default=None, 
        metadata={"help": "Training data file path (.txt, .csv, etc)."}
    )
    max_seq_length: Optional[int] = field(
        default=32,
        metadata={"help": "Max input sequence length after tokenization."}
    )
    pad_to_max_length: bool = field(
        default=False,
        metadata={"help": "Pad all samples to max_seq_length or not."}
    )
    mlm_probability: float = field(
        default=0.15,
        metadata={"help": "Ratio of tokens to mask if `do_mlm` is True."}
    )

    def __post_init__(self):
        if self.dataset_name is None and self.train_file is None:
            raise ValueError("Need either a dataset_name or a train_file.")


@dataclass
class OurTrainingArguments(TrainingArguments):
    eval_transfer: bool = field(
        default=False,
        metadata={"help": "Evaluate transfer tasks (MR, CR, TREC, etc.) during validation if True."}
    )

    @cached_property
    # @torch_required - this is not available in the current version of transformers
    def _setup_devices(self) -> "torch.device":
        logger.info("PyTorch: setting up devices")
        if self.no_cuda:
            device = torch.device("cpu")
            self._n_gpu = 0
        elif is_torch_tpu_available():
            import torch_xla.core.xla_model as xm
            device = xm.xla_device()
            self._n_gpu = 0
        elif self.local_rank == -1:
            device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
            self._n_gpu = torch.cuda.device_count()
        else:
            if self.deepspeed:
                from .integrations import is_deepspeed_available

                if not is_deepspeed_available():
                    raise ImportError("--deepspeed requires deepspeed: `pip install deepspeed`.")
                import deepspeed
                deepspeed.init_distributed()
            else:
                torch.distributed.init_process_group(backend="nccl")
            device = torch.device("cuda", self.local_rank)
            self._n_gpu = 1

        if device.type == "cuda":
            torch.cuda.set_device(device)

        return device


def main():
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, OurTrainingArguments))
    if len(sys.argv) == 2 and sys.argv[1].endswith(".json"):
        # If we pass a single JSON file, parse arguments from it
        model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.abspath(sys.argv[1]))
    else:
        # Otherwise, parse from command line
        model_args, data_args, training_args = parser.parse_args_into_dataclasses()

    if (
        os.path.exists(training_args.output_dir)
        and os.listdir(training_args.output_dir)
        and training_args.do_train
        and not training_args.overwrite_output_dir
    ):
        raise ValueError(
            f"Output directory ({training_args.output_dir}) already exists and is not empty. "
            "Use --overwrite_output_dir to overcome."
        )

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO if is_main_process(training_args.local_rank) else logging.WARN,
    )
    logger.warning(
        f"Process rank: {training_args.local_rank}, device: {training_args.device}, n_gpu: {training_args.n_gpu} "
        f"distributed training: {bool(training_args.local_rank != -1)}, 16-bits training: {training_args.fp16}"
    )

    if is_main_process(training_args.local_rank):
        transformers.utils.logging.set_verbosity_info()
        transformers.utils.logging.enable_default_handler()
        transformers.utils.logging.enable_explicit_format()
    logger.info("Training/evaluation parameters %s", training_args)

    set_seed(training_args.seed)

    # ============ Load Datasets ============
    data_files = {}
    if data_args.train_file is not None:
        data_files["train"] = data_args.train_file
    extension = data_args.train_file.split(".")[-1]
    dataset_cache_prefix = data_args.train_file.split("/")[-1]
    if extension == "txt":
        extension = "text"
    if extension == "csv":
        # Adjust if using tsv, etc.
        dataset_cache_prefix = dataset_cache_prefix.split(".")[-2]
        datasets = load_dataset(
            extension,
            data_files=data_files,
            cache_dir=f"../DATA/cache/{dataset_cache_prefix}",
            delimiter="\t" if "tsv" in data_args.train_file else ","
        )
    else:
        logger.info("Loading via HuggingFace datasets... (assuming script or similar).")
        datasets = load_dataset(
            data_args.train_file,
            cache_dir=f"../DATA/cache/{dataset_cache_prefix}"
        )

    datasets = datasets.shuffle(seed=42)

    # ============ Load Model/Tokenizer ============
    config_kwargs = {
        "cache_dir": model_args.cache_dir,
        "revision": model_args.model_revision,
        "use_auth_token": True if model_args.use_auth_token else None,
    }
    if model_args.config_name:
        config = AutoConfig.from_pretrained(model_args.config_name, **config_kwargs)
    elif model_args.model_name_or_path:
        config = AutoConfig.from_pretrained(model_args.model_name_or_path, **config_kwargs)
    else:
        # import ipdb; ipdb.set_trace()
        config = CONFIG_MAPPING[model_args.model_type]()
        logger.warning("Instantiating new config from scratch.")

    tokenizer_kwargs = {
        "cache_dir": model_args.cache_dir,
        "use_fast": model_args.use_fast_tokenizer,
        "revision": model_args.model_revision,
        "use_auth_token": True if model_args.use_auth_token else None,
    }
    if model_args.tokenizer_name:
        tokenizer = AutoTokenizer.from_pretrained(model_args.tokenizer_name, **tokenizer_kwargs)
    elif model_args.model_name_or_path:
        tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path, **tokenizer_kwargs)
    else:
        raise ValueError("No tokenizer provided; cannot train from scratch in this script.")

    # Build model
    if model_args.model_name_or_path:
        if 'roberta' in model_args.model_name_or_path.lower():
            model = RobertaForCL.from_pretrained(
                model_args.model_name_or_path,
                from_tf=bool(".ckpt" in model_args.model_name_or_path),
                config=config,
                cache_dir=model_args.cache_dir,
                revision=model_args.model_revision,
                use_auth_token=True if model_args.use_auth_token else None,
                model_args=model_args
            )
        elif 'bert' in model_args.model_name_or_path.lower():
            model = BertForCL.from_pretrained(
                model_args.model_name_or_path,
                from_tf=bool(".ckpt" in model_args.model_name_or_path),
                config=config,
                cache_dir=model_args.cache_dir,
                revision=model_args.model_revision,
                use_auth_token=True if model_args.use_auth_token else None,
                model_args=model_args
            )
            if model_args.do_mlm:
                # Copy head from a standard BertForPreTraining
                pretrained_model = BertForPreTraining.from_pretrained(model_args.model_name_or_path)
                model.lm_head.load_state_dict(pretrained_model.cls.predictions.state_dict())
        else:
            raise NotImplementedError("Model name should contain 'roberta' or 'bert' for this script.")
    else:
        logger.info("Training new model from scratch.")
        model = AutoModelForMaskedLM.from_config(config)

    model.resize_token_embeddings(len(tokenizer))

    # ============ Preprocess Dataset ============
    column_names = datasets["train"].column_names
    sent2_cname = None
    if len(column_names) == 2:
        sent0_cname, sent1_cname = column_names[0], column_names[1]
    elif len(column_names) == 3:
        sent0_cname, sent1_cname, sent2_cname = column_names[0], column_names[1], column_names[2]
    elif len(column_names) == 1:
        sent0_cname = column_names[0]
        sent1_cname = column_names[0]
    else:
        sent0_cname, sent1_cname, sent2_cname = column_names[0], column_names[1], column_names[3]

    def prepare_features(examples):
        total = len(examples[sent0_cname])
        # Basic cleaning for None entries
        for idx in range(total):
            if examples[sent0_cname][idx] is None:
                examples[sent0_cname][idx] = " "
            if examples[sent1_cname][idx] is None:
                examples[sent1_cname][idx] = " "

        sentences = examples[sent0_cname] + examples[sent1_cname]
        if sent2_cname is not None:
            for idx in range(total):
                if examples[sent2_cname][idx] is None:
                    examples[sent2_cname][idx] = " "
            sentences += examples[sent2_cname]

        sent_features = tokenizer(
            sentences,
            max_length=data_args.max_seq_length,
            truncation=True,
            padding="max_length" if data_args.pad_to_max_length else False,
        )

        features = {}
        if sent2_cname is not None:
            # 3-sentence scenario
            for key in sent_features:
                features[key] = [
                    [
                        sent_features[key][i],
                        sent_features[key][i + total],
                        sent_features[key][i + total*2]
                    ]
                    for i in range(total)
                ]
        else:
            # 2-sentence scenario
            for key in sent_features:
                features[key] = [
                    [sent_features[key][i], sent_features[key][i + total]]
                    for i in range(total)
                ]
        return features

    if training_args.do_train:
        train_dataset = datasets["train"].map(
            prepare_features,
            batched=True,
            num_proc=data_args.preprocessing_num_workers,
            remove_columns=column_names,
            load_from_cache_file=not data_args.overwrite_cache,
        )

    @dataclass
    class OurDataCollatorWithPadding:
        tokenizer: PreTrainedTokenizerBase
        padding: Union[bool, str, PaddingStrategy] = True
        max_length: Optional[int] = None
        pad_to_multiple_of: Optional[int] = None
        mlm: bool = True
        mlm_probability: float = 0.15

        def __call__(self, features: List[Dict[str, Union[List[int], List[List[int]], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
            special_keys = ["input_ids", "attention_mask", "token_type_ids", "mlm_input_ids", "mlm_labels"]
            bs = len(features)
            if bs == 0:
                return {}
            num_sent = len(features[0]["input_ids"])

            flat_features = []
            for feature in features:
                for i in range(num_sent):
                    flat_features.append({
                        k: feature[k][i] if k in special_keys else feature[k]
                        for k in feature
                    })

            batch = self.tokenizer.pad(
                flat_features,
                padding=self.padding,
                max_length=self.max_length,
                pad_to_multiple_of=self.pad_to_multiple_of,
                return_tensors="pt",
            )

            if model_args.do_mlm:
                batch["mlm_input_ids"], batch["mlm_labels"] = self.mask_tokens(batch["input_ids"])

            # Reshape to (bs, num_sent, seq_len)
            batch = {
                k: batch[k].view(bs, num_sent, -1) if k in special_keys else batch[k].view(bs, num_sent, -1)[:, 0]
                for k in batch
            }

            if "label" in batch:
                batch["labels"] = batch["label"]
                del batch["label"]
            if "label_ids" in batch:
                batch["labels"] = batch["label_ids"]
                del batch["label_ids"]

            return batch

        def mask_tokens(
            self, inputs: torch.Tensor, special_tokens_mask: Optional[torch.Tensor] = None
        ) -> Tuple[torch.Tensor, torch.Tensor]:
            inputs = inputs.clone()
            labels = inputs.clone()
            probability_matrix = torch.full(labels.shape, self.mlm_probability)
            if special_tokens_mask is None:
                special_tokens_mask = [
                    self.tokenizer.get_special_tokens_mask(val, already_has_special_tokens=True)
                    for val in labels.tolist()
                ]
                special_tokens_mask = torch.tensor(special_tokens_mask, dtype=torch.bool)
            else:
                special_tokens_mask = special_tokens_mask.bool()

            probability_matrix.masked_fill_(special_tokens_mask, value=0.0)
            masked_indices = torch.bernoulli(probability_matrix).bool()
            labels[~masked_indices] = -100  # ignore these in the loss

            # 80% replace with [MASK]
            indices_replaced = torch.bernoulli(torch.full(labels.shape, 0.8)).bool() & masked_indices
            inputs[indices_replaced] = self.tokenizer.convert_tokens_to_ids(self.tokenizer.mask_token)

            # 10% random
            indices_random = torch.bernoulli(torch.full(labels.shape, 0.5)).bool() & masked_indices & ~indices_replaced
            random_words = torch.randint(len(self.tokenizer), labels.shape, dtype=torch.long)
            inputs[indices_random] = random_words[indices_random]

            # 10% remain unchanged
            return inputs, labels

    data_collator = (
        default_data_collator if data_args.pad_to_max_length
        else OurDataCollatorWithPadding(
            tokenizer=tokenizer,
            mlm=model_args.do_mlm,
            mlm_probability=data_args.mlm_probability,
        )
    )

    # ============ Trainer ============
    trainer = CLTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset if training_args.do_train else None,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )
    trainer.model_args = model_args  # so the trainer sees our custom arguments

    # ============ Training ============
    if training_args.do_train:
        model_path = (
            model_args.model_name_or_path
            if (model_args.model_name_or_path is not None and os.path.isdir(model_args.model_name_or_path))
            else None
        )
        train_result = trainer.train(model_path=model_path)
        trainer.save_model()

        output_train_file = os.path.join(training_args.output_dir, "train_results.txt")
        if trainer.is_world_process_zero():
            with open(output_train_file, "w") as writer:
                logger.info("***** Train results *****")
                for key, value in sorted(train_result.metrics.items()):
                    logger.info(f"  {key} = {value}")
                    writer.write(f"{key} = {value}\n")
            trainer.state.save_to_json(os.path.join(training_args.output_dir, "trainer_state.json"))

    # ============ Evaluation ============
    results = {}
    if training_args.do_eval:
        logger.info("*** Evaluate ***")
        results = trainer.evaluate(eval_senteval_transfer=True)

        output_eval_file = os.path.join(training_args.output_dir, "eval_results.txt")
        if trainer.is_world_process_zero():
            with open(output_eval_file, "w") as writer:
                logger.info("***** Eval results *****")
                for key, value in sorted(results.items()):
                    logger.info(f"  {key} = {value}")
                    writer.write(f"{key} = {value}\n")

    return results

def _mp_fn(index):
    main()

if __name__ == "__main__":
    main()
